test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>
  
#amazon:
  #service: S3
  #access_key_id: <%= Rails.application.credentials.dig(:aws, 'AKIAQGDERNDHQK5SYS6Z') %>
  #secret_access_key: <%= Rails.application.credentials.dig(:aws, 'nvGv2CJoaUTxsS4g6DIAvWdmuMMo/pZL5M5xMS+/') %>
  #region: us-east-1
  #bucket: shota0523
  
amazon:
  service: S3
  access_key_id:     <%= ENV['AWS_ACCESS_KEY'] %>
  secret_access_key: <%= ENV['AWS_SECRET_KEY'] %>
  region:            <%= ENV['AWS_REGION'] %>
  bucket:            <%= ENV['AWS_BUCKET'] %>
